server:
  port: ${CUSTOM.SERVER.PORT:9005}

spring:
  security:
    oauth2:
      client:
        provider:
          mitocode-realm:
            issuer-uri: http://localhost:8080/realms/mitocode-realm
        registration:
          mitocode-realm:
            provider: mitocode-realm
            client-name: mitocode-client
            client-id: mitocode-client
            client-secret: t5P9ONPQjZvLSFCsB4GaQ7xap85wxh3S
            scope: openid
            authorization-grant-type: authorization_code
