server:
  port: 9010

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: admin
      password: pass
      authentication-database: admin
      #uri: mongodb://admin:pass@localhost:27017/mitocode?authSource=admin
      
